AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Metrics/CyclomaticComplexity: 
  Enabled: false
Layout/LineLength: 
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false